/**
 * Attract-Mode Frontend
 *
 * @package Signal
 * @global
 */

// -------------------------------------------------------------------------------------

local signalActions = [
    "add_favourite",
    "add_tags",
    "back",
    "configure",
    "custom1",
    "custom10",
    "custom2",
    "custom3",
    "custom4",
    "custom5",
    "custom6",
    "custom7",
    "custom8",
    "custom9",
    "displays_menu",
    "down",
    "edit_game",
    "exit_to_desktop",
    "exit",
    "filters_menu",
    "intro",
    "layout_options",
    "left",
    "next_display",
    "next_favourite",
    "next_filter",
    "next_game",
    "next_letter",
    "next_page",
    "prev_display",
    "prev_favourite",
    "prev_filter",
    "prev_game",
    "prev_letter",
    "prev_page",
    "random_game",
    "reload",
    "replay_last_game",
    "reset_window",
    "right",
    "screen_saver",
    "screenshot",
    "select",
    "toggle_flip",
    "toggle_layout",
    "toggle_movie",
    "toggle_mute",
    "toggle_rotate_left",
    "toggle_rotate_right",
    "up",
];
